language: java
script: gradle dist
sudo: false
deploy:
  provider: releases
  api_key:
    secure: EEBKTT8mI8twLPo5DG9sWdRPu0BQj0ssXE6jvIQqNst4va4XVEVVvFh2tuLNwxpG0A3UNI1AS7cTU4QnSzzKDYfn9bMMZOTyobgb2cMFl+TveYz+Gz6xK13FqeVvHM3VXYF4940I2ZmcZ1seAR4XwtKPiaydNUfuvfiZyVDyrbY=
  skip_cleanup: true
  file: build/distributions/docbook-xslt20-resources-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
